config/routes.rb
Rails.application.routes.draw do
  root 'currencies#show', id:'BRL'
  resources :currencies, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/currency_controller.rb
class CurrenciesController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/currencies/show.html.erb
<h1>Values of Currencies</h1>
  <a class= "btn btn-primary" href=<%= currency_path('BRL') %> role="button">BRL</a>
  <a class= "btn btn-primary" href=<%= currency_path('BRL') %> role="button">EUR</a>
  <a class= "btn btn-primary" href=<%= currency_path('BRL') %> role="button">USD</a>
  <%= link_to_if(params[:id], “Graph of #{params[:id]}”, “https://en.wikipedia.org/wiki/#{params[:id]}") %>
    <% if params[:id] %>
    <h3> Graph of <%= link_to("#{params[:id]}", "https://en.wikipedia.org/wiki/#{params[:id]}") %> </h3>
    <% else %>
    <h3> Choose a currency please: >/h3>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <div class='page-header'>
    <h1> Valuation of Currencies</h1>
    </div>
    <title>CurrencyValuation</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css">
  </head>

  <body>
    <div class="container">
    <%= yield %>
    </div>
    <div class="btn-toolbar" style="display: flex; margin-top: 15px;">
      <div style="margin: auto;">
        <a class="btn btn-success" href=<%= currency_path('BRL') %> role="button">BRL</a>
        <a class="btn btn-success" href=<%= currency_path('EUR') %> role="button">EUR</a>
        <a class="btn btn-success" href=<%= currency_path('USD') %> role="button">USD</a>
      </div>
    </div>
    <%= yield %>
  </body>
</html>